[window]
padding.x = 10
padding.y = 10


decorations = "None"

opacity = 0.8

option_as_alt="Both"

startup_mode = "Maximized"

title ="86LAK"


save_to_clipboard = true

[font.normal]
family = "Hack Nerd Font Mono"
