#!/usr/bin/env bash

# Create a new tmux session in detached mode named '86'
tmux new-session -d -s 86
tmux split-window -h

tmux split-window -v
# Resize the top-right pane before running cmatrix
tmux select-pane -t 1
total_height=$(tmux display-message -p '#{window_height}')
new_height=$((total_height / 8))
tmux resize-pane -y $new_height

# Run 'cmatrix -C red' in the top-right pane
tmux select-pane -t 1
tmux send-keys "cmatrix -C red" C-m

# Run 'neofetch' in the bottom-right pane
tmux select-pane -t 2
tmux send-keys "neofetch" C-m


# Select the original (left) pane
tmux select-pane -t 0
# tmux send-keys "awk 'print "\033[31m"$0"\033[033[033["}' ~/Applications/dotfiles/shell/8686" C-m

awk_cmd='awk '\''{print "\033[31m" $0 "\033[0m"}'\'' ~/Applications/dotfiles/shell/8686'
tmux send-keys "stty -echo" C-m
tmux send-keys "clear" C-m
tmux send-keys "$awk_cmd" C-m
tmux send-keys "stty echo" C-m


# Attach to the tmux session
tmux attach-session -t 86
